### ISSUE TITLE
Proper way to run plv8_startup()?

### ISSUE THREAD

**Issue by jamesdixon** [slardiere/plv8_modules#1]
Hi, I've been trying to use the code referenced in the article that you built your module from and am having an issue where it doesn't seem that plv8_startup() is being run. When I do run it, it doesn't appear to be available on all connections (for example, if I run it in my sql editor, the library becomes available, but not in my webapp). Any help would really be appreciated!

**Comment by slardiere** [comment]
Indeed, something missing in the README. Please, add : 

```
plv8.start_proc = 'plv8_startup'
```

to you postgresql.conf file, and restart the instance. I'll add it to the README.

**Comment by jamesdixon** [comment]
Perfect. Thanks!
